real_ground= turtle.clone()
soil = turtle.clone()
turtle.register_shape("realground.gif")
turtle.register_shape("soil.gif")
real_ground.shape("realground.gif")
soil.shape("soil.gif")
realground.goto("")
